[workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]
preview = ["pixi-build"]

[package]
name = "pixi-nvhpc-recipe"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-rattler-build", version = "*" }
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]

[tasks]

[dependencies]
cxx-compiler = ">=1.9.0,<2"
pixi-nvhpc-recipe = {path = "."}
