name: Tmate debugging
on: [workflow_dispatch]
jobs:
  explore:
    # runs-on: ubuntu-latest
    runs-on: gpu
    steps:
    - uses: prefix-dev/setup-pixi@v0.8.1
      with:
        pixi-version: v0.40.3
        log-level: v
        # cache: true
    - uses: actions/checkout@v4
    # - run: curl -fsSL https://pixi.sh/install.sh | bash
    - name: Setup tmate session 
      uses: mxschmitt/action-tmate@v3
